name: AlwaysData.com Deployment
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        exclude: |
          **/.git*
          **/.git*/**
          **/*.go*
          *.go
          **/*.git*/**

    - name: Check binary file, ipaddress, and restart sites
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.sshhost }}
        username: ${{ secrets.sshusername }}
        password: ${{ secrets.sshpassword }}
        port: ${{ secrets.sshport }}
        script: |
          composer self-update --2
          composer --version
          composer install --no-dev --optimize-autoloader
          curl https://icanhazip.com/
          curl -X POST --basic --user "${{ secrets.apikey }}:" https://api.alwaysdata.com/v1/site/${{ secrets.appid }}/restart/