name: AlwaysData.com Deployment
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # Ganti dengan versi PHP yang sesuai
        extensions: openssl, zip, fileinfo, pgsql, pdo_pgsql # Tambahkan ekstensi yang dibutuhkan

    - name: Install Composer
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Generate APP_KEY
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate --force

    - name: Cache Configuration
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: chmod storage and bootstrap/cache
      run: |
        sudo chmod -R 775 storage
        sudo chmod -R 775 bootstrap/cache

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        exclude: |
          **/.git*
          **/.git*/**
          **/*.go*
          *.go
          **/*.git*/**

    - name: Check binary file, ipaddress, and restart sites
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.sshhost }}
        username: ${{ secrets.sshusername }}
        password: ${{ secrets.sshpassword }}
        port: ${{ secrets.sshport }}
        script: |
          ls -l gocroot
          curl https://icanhazip.com/
          curl -X POST --basic --user "${{ secrets.apikey }}:" https://api.alwaysdata.com/v1/site/${{ secrets.appid }}/restart/